variable "vprefix" {}
variable "vrgs" {}
variable "vvnet" {}
variable "vsubnet" {}
variable "vnsg" {}
variable "vnsgass" {}
variable "vpublicip" {}
variable "vbastion" {}
variable "vvmwin" {}
variable "vnic" {}